config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
  resources :boards, only: [:show, :create, :index, :destroy] do
    post 'click_cell', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :rows, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :columns, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :number_of_mines, presence: true, numericality: { only_integer: true, greater_than: 0 }

  has_many :board_cells, dependent: :destroy
end

app/models/board_cell.rb
class BoardCell < ApplicationRecord
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    sort_order = params[:sort_order] || 'desc'
    @boards = Board.order(created_at: sort_order)
    @boards = @boards.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
    per_page = params[:per_page] || 10
    @boards = @boards.page(params[:page]).per(per_page)
  end

  def show
    @board = Board.find(params[:id])
    start_row = params[:start_row].to_i || 0
    start_column = params[:start_column].to_i || 0
    limit_rows = (params[:limit_rows] || 20).to_i
    limit_columns = (params[:limit_columns] || 20).to_i
    end_row = [start_row + limit_rows - 1, @board.rows - 1].min
    end_column = [start_column + limit_columns - 1].min

    @board_cells = @board.board_cells
                         .where(row: start_row..end_row, column: start_column..end_column)
                         .index_by { |cell| [cell.row, cell.column] }
  end

  def click_cell
    @board = Board.find(params[:id])
    row = params[:row].to_i
    column = params[:column].to_i

    cell = @board.board_cells.find_or_initialize_by(row: row, column: column)
    cell.clicked = true
    cell.save

    mine_found = cell.mine
    render json: { mine_found: mine_found }
  end

  def create
    user = User.find_or_create_by(email: params[:user][:email])
    @board = Board.new(board_params.except(:email))
    @board.user = user
    if @board.save
      generate_mines(@board)
      redirect_to @board
    else
      @boards = Board.order(created_at: :desc).limit(5)
      render 'home/index'
    end
  end

  private

  def board_params
    params.require(:board).permit(:name, :rows, :columns, :number_of_mines)
  end

  def generate_mines(board)
    ActiveRecord::Base.transaction do
      total_cells = board.rows * board.columns
      mine_positions = (0...total_cells).to_a.sample(board.number_of_mines)
      board_cells = mine_positions.map do |pos|
        row = pos / board.columns
        column = pos % board.columns
        BoardCell.create(board: board, row: row, column: column, mine: true)
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @boards = Board.order(created_at: :desc).limit(5)
    @board = Board.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :email ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<div class="relative flex flex-col items-center w-full gap-10 py-10 px-4">
  <%= link_to root_path, class: "absolute top-4 left-4 bg-gray-500 hover:bg-gray-700 text-white font-light py-2 px-4 rounded flex items-center gap-2" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
    </svg>
    <span>Back to Home</span>
  <% end %>
  <h1 class="text-4xl font-medium">Minesweeper Boards</h1>
  <%= form_with url: boards_path, method: :get, local: true, class: 'w-full max-w-xl' do %>
    <div class="flex items-center gap-4">
      <%= text_field_tag :search, params[:search], placeholder: "Search by name", class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      <%= submit_tag 'Search', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    </div>
    <div class="flex items-center gap-4 mt-4">
      <div class="flex items-center justify-self-center gap-4">
        <label for="per_page" class="font-bold">Items per page:</label>
        <select id="per_page" name="per_page" class="border rounded pl-6" onchange="this.form.submit()">
          <% [5, 10, 20, 50].each do |count| %>
            <option value="<%= count %>" <%= 'selected' if count == (params[:per_page] || 10).to_i %>><%= count %></option>
          <% end %>
        </select>
      </div>
      <div class="flex items-center justify-self-center gap-4">
        <label for="sort_order" class="font-bold">Sort by:</label>
        <select id="sort_order" name="sort_order" class="border rounded pl-6" onchange="this.form.submit()">
          <option value="desc" <%= 'selected' if params[:sort_order] == 'desc' %>>Newest First</option>
          <option value="asc" <%= 'selected' if params[:sort_order] == 'asc' %>>Oldest First</option>
        </select>
      </div>
    </div>
  <% end %>
  <% if @boards.any? %>
    <div class="w-full flex flex-col items-center overflow-x-auto">
      <table class="w-full bg-white max-w-5xl shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <thead>
          <tr>
            <th class="border-b-2 pb-2 text-left px-4">Name</th>
            <th class="border-b-2 pb-2 text-center pr-4">Rows</th>
            <th class="border-b-2 pb-2 text-center pr-4">Columns</th>
            <th class="border-b-2 pb-2 text-center pr-4">Mines</th>
            <th class="border-b-2 pb-2 text-center pr-4">Checked Cells</th>
            <th class="border-b-2 pb-2 text-center pr-4">Found Mines</th>
            <th class="border-b-2 pb-2 text-left pr-4">Email</th>
            <th class="border-b-2 pb-2 text-left pr-4">Created At</th>
            <th class="border-b-2 pb-2 text-left px-4">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @boards.each do |board| %>
            <tr>
              <td class="border-b pb-2 px-4"><%= board.name %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.rows %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.columns %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.number_of_mines %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.board_cells.where(clicked: true).count %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.board_cells.where(clicked: true, mine: true).count %></td>
              <td class="border-b pb-2 pr-4"><%= board.user.email %></td>
              <td class="border-b pb-2 pr-4"><%= board.created_at.localtime.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <td class="border-b pb-2 px-4">
                <%= link_to 'Show', board_path(board), class: 'text-blue-500 hover:text-blue-700' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @boards %>
  <% else %>
    <p class="text-center text-gray-500">No boards available.</p>
  <% end %>
</div>

app/views/boards/show.html.erb
<div class="relative flex flex-col items-center w-full gap-8 py-10 px-4">
  <%= link_to root_path, class: "absolute top-4 left-4 bg-gray-500 hover:bg-gray-700 text-white font-light py-2 px-4 rounded flex items-center gap-2" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
    </svg>
    <span>Back to Home</span>
  <% end %>
  <div class="flex flex-col items-center gap-4 text-center">
    <h1 class="text-4xl font-medium">Minesweeper Board</h1>
    <h2 class="text-xl font-light">Name of the Board: <%= @board.name %></h2>
  </div>

  <div class="flex items-center gap-4 text-center text-base font-semibold">
    <h2>Rows: <span class="font-light"><%= @board.rows %></span></h2>
    <h2>Columns: <span class="font-light"><%= @board.columns %></span></h2>
    <h2>Mines: <span class="font-light"><%= @board.number_of_mines %></span></h2>
    <h2>Email: <span class="font-light"><%= @board.user.email %></span></h2>
  </div>

  <% start_row = params[:start_row].to_i || 0 %>
  <% start_column = params[:start_column].to_i || 0 %>
  <% limit_rows = (params[:limit_rows] || 20).to_i %>
  <% limit_columns = (params[:limit_columns] || 20).to_i %>
  <% end_row = [start_row + limit_rows - 1, @board.rows - 1].min %>
  <% end_column = [start_column + limit_columns - 1].min %>

  <div class="flex flex-col items-center gap-2 w-full">
    <div class="flex gap-2 mb-4 items-center">
      <label for="limit_rows" class="font-bold">Rows:</label>
      <select id="limit_rows" name="limit_rows" class="border rounded pl-6" onchange="location.href='?limit_rows=' + this.value + '&limit_columns=' + document.getElementById('limit_columns').value + '&start_row=<%= start_row %>&start_column=<%= start_column %>'">
        <% (10..50).step(10).each do |i| %>
          <option value="<%= i %>" <%= 'selected' if i == limit_rows %>><%= i %></option>
        <% end %>
      </select>
      <label for="limit_columns" class="font-bold">Columns:</label>
      <select id="limit_columns" name="limit_columns" class="border rounded pl-6" onchange="location.href='?limit_rows=' + document.getElementById('limit_rows').value + '&limit_columns=' + this.value + '&start_row=<%= start_row %>&start_column=<%= start_column %>'">
        <% (10..50).step(10).each do |i| %>
          <option value="<%= i %>" <%= 'selected' if i == limit_columns %>><%= i %></option>
        <% end %>
      </select>
    </div>
    <%# Now not play mode %>
    <button id="toggle-play" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded hidden">Play</button> 
    <%= link_to '⬆️', board_path(@board, start_row: [start_row - limit_rows, 0].max, start_column: start_column, limit_rows: limit_rows, limit_columns: limit_columns), class: "arrow-button #{start_row <= 0 ? 'bg-gray-300 pointer-events-none' : 'bg-blue-50 hover:bg-blue-200'}", disabled: start_row <= 0 %>
    <div class="flex items-center gap-2 max-w-full overflow-x-auto">
      <%= link_to '⬅️', board_path(@board, start_row: start_row, start_column: [start_column - limit_columns, 0].max, limit_rows: limit_rows, limit_columns: limit_columns), class: "arrow-button #{start_column <= 0 ? 'bg-gray-300 pointer-events-none'  : 'bg-blue-50 hover:bg-blue-200'}", disabled: start_column <= 0 %>
      <div class="bg-white shadow-xl border-t border-solid border-gray-200 rounded-xl p-4">
        <div class="flex">
          <div class="cell"></div>
          <% (start_column..end_column).each do |column| %>
            <div class="cell <%= column >= 1000 ? 'text-[10px]' : column >= 100 ? 'text-xs' : 'text-base' %> <%= column >= 1000 ? 'font-extralight' : column >= 100 ? 'font-light' : 'font-medium' %>"><%= column + 1 %></div>
          <% end %>
        </div>
        <% (start_row..end_row).each do |row| %>
          <div class="flex">
            <div class="cell <%= row >= 1000 ? 'text-[10px]' : row >= 100 ? 'text-xs' : 'text-base' %> <%= row >= 1000 ? 'font-extralight' : row >= 100 ? 'font-light' : 'font-medium' %>"><%= row + 1 %></div>
            <% (start_column..end_column).each do |column| %>
              <% cell = @board_cells[[row, column]] %>
              <div class="border cell leading-none text-lg" id="cell-<%= row %>-<%= column %>">
                <% if cell %>
                  <% if cell.clicked %>
                    <%= cell.mine ? '💣' : '✅' %>
                  <% else %>
                    <span class="mine-hidden"><%= cell.mine ? '💣' : '⬜️' %></span>
                    <%= button_to '⬜️', click_cell_board_path(@board, row: row, column: column, start_row: start_row, start_column: start_column, limit_rows: limit_rows, limit_columns: limit_columns), method: :post, remote: true, class: "block w-full h-full p-0 border-0 bg-transparent mine-button", style: "display: none;" %>
                  <% end %>
                <% else %>
                  <span class="mine-hidden">⬜️</span>
                  <%= button_to '⬜️', click_cell_board_path(@board, row: row, column: column, start_row: start_row, start_column: start_column, limit_rows: limit_rows, limit_columns: limit_columns), method: :post, remote: true, class: "block w-full h-full p-0 border-0 bg-transparent mine-button", style: "display: none;" %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= link_to '➡️', board_path(@board, start_row: start_row, start_column: [start_column + limit_columns, @board.columns - limit_columns].min, limit_rows: limit_rows, limit_columns: limit_columns), class: "arrow-button #{start_column + limit_columns >= @board.columns ? 'bg-gray-300 pointer-events-none' : 'bg-blue-50 hover:bg-blue-200'}", disabled: start_column + limit_columns >= @board.columns %>
    </div>
    <%= link_to '⬇️', board_path(@board, start_row: [start_row + limit_rows, @board.rows - limit_rows].min, start_column: start_column, limit_rows: limit_rows, limit_columns: limit_columns), class: "arrow-button #{start_row + limit_rows >= @board.rows ? 'bg-gray-300 pointer-events-none' : 'bg-blue-50 hover:bg-blue-200'}", disabled: start_row + limit_rows >= @board.rows %>
  </div>
</div>
<div id="snackbar" class="hidden fixed z-10 w-1/2 bottom-4 left-1/2 transform -translate-x-1/2 bg-green-500 text-white text-center py-2 px-4 rounded">
  Congratulations! You found a mine 💥!
</div>

  <%# <script>
    var x = document.getElementById("snackbar");
    x.style.display = "block";
    setTimeout(function(){ x.style.display = "none"; }, 3000);
  </script> %>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const togglePlayButton = document.getElementById("toggle-play");
    const mineButtons = document.querySelectorAll(".mine-button");
    const mineHiddenSpans = document.querySelectorAll(".mine-hidden");

    togglePlayButton.addEventListener("click", function() {
      mineButtons.forEach(button => button.style.display = "block");
      mineHiddenSpans.forEach(span => span.style.display = "none");
      togglePlayButton.style.display = "none";
    });
  });
</script>

app/views/home/index.html.erb
<div class="flex flex-col items-center w-full gap-10 py-10 px-4">
  <div class="flex flex-col items-center gap-4 text-center">
    <h1 class="text-4xl font-medium">Welcome to the Minesweeper Game</h1>
    <h2 class="text-xl font-light">Generate a New Minesweeper Board</h2>
  </div>
  <%= form_with model: @board, url: boards_path, local: true, class:'w-full flex flex-col items-center' do |form| %>
    <div class="w-full max-w-xl bg-white shadow-xl border-t border-solid border-gray-200 rounded-2xl px-8 pt-8 pb-6 gap-6 flex flex-col">
      <div>
        <%= form.label :name, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div>
        <%= form.label :rows, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.number_field :rows, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div>
        <%= form.label :columns, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.number_field :columns, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div>
        <%= form.label :number_of_mines, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.number_field :number_of_mines, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div>
        <%= form.label :email, class: 'block text-gray-700 text-sm font-bold mb-2' %>
        <%= form.email_field :email, name: 'user[email]', class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="flex justify-center items-center">
        <%= form.submit 'Generate Board', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
      </div>
    </div>
  <% end %>
  <h2 class="text-2xl font-medium mt-8 text-center">Previously Generated Minesweeper Boards</h2>
  <% if @boards.any? %>
    <div class="w-full flex flex-col items-center overflow-x-auto">
      <table class="w-full bg-white max-w-5xl shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <thead>
          <tr>
            <th class="border-b-2 pb-2 text-left px-4">Name</th>
            <th class="border-b-2 pb-2 text-center pr-4">Rows</th>
            <th class="border-b-2 pb-2 text-center pr-4">Columns</th>
            <th class="border-b-2 pb-2 text-center pr-4">Mines</th>
            <th class="border-b-2 pb-2 text-center pr-4">Checked Cells</th>
            <th class="border-b-2 pb-2 text-center pr-4">Found Mines</th>
            <th class="border-b-2 pb-2 text-left pr-4">Email</th>
            <th class="border-b-2 pb-2 text-left px-4">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @boards.each do |board| %>
            <tr>
              <td class="border-b pb-2 px-4"><%= board.name %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.rows %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.columns %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.number_of_mines %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.board_cells.where(clicked: true).count %></td>
              <td class="border-b pb-2 text-center pr-4"><%= board.board_cells.where(clicked: true, mine: true).count %></td>
              <td class="border-b pb-2 pr-4"><%= board.user.email %></td>
              <td class="border-b pb-2 px-4">
                <%= link_to 'Show', board_path(board), class: 'text-blue-500 hover:text-blue-700' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <a href="<%= boards_path %>" class="text-blue-500 hover:text-blue-700">View Full List of Minesweeper Boards</a>
  <% else %>
    <p class="text-center text-gray-500">No boards available.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Minesweeper" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="flex flex-col min-h-svh">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>